// file auto-generated by assets packer, do not modify directly
#ifndef ASSETS_H
#define ASSETS_H

#include <core/data.h>
#include <core/defs.h>

#define ASSET_MUSIC_TEMPO 60

#define ASSET_COVER data_flash(0x0000)

#define ASSET_FONT_5X7 data_flash(0x0181)
#define ASSET_FONT_7X7 data_flash(0x0349)

#endif
