// file auto-generated by assets packer, do not modify directly
#ifndef ASSETS_H
#define ASSETS_H

#include <core/data.h>
#include <core/defs.h>
#include <core/flash.h>

#define ASSET_MUSIC_TEMPO 80
#define ASSET_TILESET_MAP_BOTTOM_SIZE 144

#define ASSET_COVER data_flash(0x0000)

#define ASSET_MUSIC_THEME0 data_flash(0x0d07)
#define ASSET_MUSIC_THEME1 data_flash(0x0e7e)
#define ASSET_MUSIC_MENU data_flash(0x1116)
#define ASSET_MUSIC_FAIL data_flash(0x11d9)
#define ASSET_MUSIC_COMPLETE data_flash(0x1209)

#define ASSET_FONT_5X7 data_flash(0x125d)
#define ASSET_FONT_7X7 data_flash(0x1425)

#define ASSET_IMAGE_ARROW_UP data_flash(0x15c1)
#define ASSET_IMAGE_ARROW_DOWN data_flash(0x15c8)
#define ASSET_IMAGE_SECRET_LEVEL data_flash(0x15cf)
#define ASSET_IMAGE_MENU data_flash(0x15e7)
#define ASSET_IMAGE_PACK_PASSWORD data_flash(0x29c5)
#define ASSET_IMAGE_PACK_LOCKED data_flash(0x2a3c)

extern const uint8_t ASSET_TILESET_MAP_BOTTOM[];
extern const uint8_t ASSET_TILESET_MAP_TOP[];

#define ASSET_IMAGE_PACK_PROGRESS_SIZE 9
#define ASSET_IMAGE_PACK_PROGRESS_ADDR 0x2abe
#define ASSET_IMAGE_PACK_PROGRESS_OFFSET 103
#define asset_image_pack_progress(n) data_flash(ASSET_IMAGE_PACK_PROGRESS_ADDR + (n) * ASSET_IMAGE_PACK_PROGRESS_OFFSET)

#define ASSET_TILESET_BOTTOM_SIZE 72
#define ASSET_TILESET_BOTTOM_ADDR 0x2e5d
#define ASSET_TILESET_BOTTOM_OFFSET 112
#define asset_tileset_bottom(n) (ASSET_TILESET_BOTTOM_ADDR + (n) * ASSET_TILESET_BOTTOM_OFFSET)

#define ASSET_TILESET_TOP_SIZE 24
#define ASSET_TILESET_TOP_ADDR 0x4ddd
#define ASSET_TILESET_TOP_OFFSET 112
#define asset_tileset_top(n) (ASSET_TILESET_TOP_ADDR + (n) * ASSET_TILESET_TOP_OFFSET)

#define ASSET_END_CAUSE_SIZE 6
extern const uint16_t ASSET_END_CAUSE[];
#define asset_end_cause(n) (ASSET_END_CAUSE[n])

#define ASSET_HELP_SIZE 48
#define ASSET_HELP_INDEX 0x4a6b5L
#define ASSET_HELP_ADDR_SIZE 2
#define asset_help(n) (({uint16_t _a; flash_read(ASSET_HELP_INDEX + (n) * ASSET_HELP_ADDR_SIZE, 2, &_a); _a;}))

#define ASSET_LEVEL_PACKS_SIZE 4
extern const uint24_t ASSET_LEVEL_PACKS[];
#define asset_level_packs(n) (ASSET_LEVEL_PACKS[n])

#endif
