
GAME_VERSION_MAJOR := 0
GAME_VERSION_MINOR := 1

DEFINES += GAME_VERSION_MAJOR=$(GAME_VERSION_MAJOR) GAME_VERSION_MINOR=$(GAME_VERSION_MINOR)

DEFINES += DIALOG_MAX_ITEMS=6

.PHONY: pack

pack:
	$(E)export PYTHONPATH="../utils"; python3 $(TARGET)/pack.py
