
DEFINES += DIALOG_MAX_ITEMS=6
DEFINES += DISPLAY_BUFFER_SIZE=2752

# disable unused encodings and graphics options
DEFINES += GRAPHICS_NO_1BIT_RAW_IMAGE \
           GRAPHICS_NO_4BIT_RAW_IMAGE \
		   GRAPHICS_NO_HORIZONTAL_IMAGE_REGION \
		   GRAPHICS_NO_TRANSPARENT_IMAGE

.PHONY: pack

pack:
	$(E)export PYTHONPATH="../utils"; python3 $(TARGET)/pack.py
