// file auto-generated by assets packer, do not modify directly
#ifndef ASSETS_H
#define ASSETS_H

#include <core/data.h>
#include <core/defs.h>

#define ASSET_SOUND_TEMPO 60

#define ASSET_COVER data_flash(0x0000)

#define ASSET_MUSIC_THEME data_flash(0x09bc)
#define ASSET_MUSIC_MENU data_flash(0x0cfc)
#define ASSET_MUSIC_GAME_OVER data_flash(0x0d7d)
#define ASSET_MUSIC_HIGH_SCORE data_flash(0x0da7)

#define ASSET_SOUND_HARD_DROP data_flash(0x0e6a)
#define ASSET_SOUND_HOLD data_flash(0x0e75)
#define ASSET_SOUND_COMBO data_flash(0x0e80)
#define ASSET_SOUND_PERFECT data_flash(0x0e8b)
#define ASSET_SOUND_TSPIN data_flash(0x0ea6)

#define ASSET_IMAGE_MENU data_flash(0x0ef2)
#define ASSET_IMAGE_TILE_GHOST data_flash(0x1e02)

#define ASSET_FONT_5X7 data_flash(0x1e0c)
#define ASSET_FONT_7X7 data_flash(0x1fd4)

#define ASSET_SOUND_CLEAR_SIZE 4
#define ASSET_SOUND_CLEAR_ADDR 0x0eb6
#define ASSET_SOUND_CLEAR_OFFSET 15
#define asset_sound_clear(n) data_flash(ASSET_SOUND_CLEAR_ADDR + (n) * ASSET_SOUND_CLEAR_OFFSET)

#endif
