// file auto-generated by assets packer, do not modify directly
#ifndef ASSETS_H
#define ASSETS_H

#include <core/data.h>
#include <core/defs.h>

#define ASSET_COVER data_flash(0x0000)

extern const uint8_t ASSET_FONT_5X7_DATA[];
#define ASSET_FONT_5X7 data_mcu(ASSET_FONT_5X7_DATA)
extern const uint8_t ASSET_FONT_7X7_DATA[];
#define ASSET_FONT_7X7 data_mcu(ASSET_FONT_7X7_DATA)

extern const uint8_t ASSET_IMAGE_ARROW_UP_DATA[];
#define ASSET_IMAGE_ARROW_UP data_mcu(ASSET_IMAGE_ARROW_UP_DATA)
extern const uint8_t ASSET_IMAGE_ARROW_DOWN_DATA[];
#define ASSET_IMAGE_ARROW_DOWN data_mcu(ASSET_IMAGE_ARROW_DOWN_DATA)

#endif
